### ISSUE TITLE
Research: why Libgdx needs to be on SNAPSHOT?

### ISSUE THREAD

**Issue by keesvandieren** [squins/gdx-backend-bytecoder#13]
ByteBuffer nativeOrder seems to not work well with Bytecoder the way libgdx does it.

We worked around that by calling BufferUtils.

How to go on with that?

**Comment by CoenRijsdijk** [comment]
Shaderprogram shaded for now, so we can use Libgdx 1.9.11 instead of a local snapshot. It's not the most clean solution, but for now it's fine

**Comment by keesvandieren** [comment]
Confirmed: works on my machine :)
