### ISSUE TITLE
Bytecoder: Identify and submit the must-have PRs of Bytecoder

### ISSUE THREAD

**Issue by keesvandieren** [squins/gdx-backend-bytecoder#16]
Collect the PRs that we have to submit and get accepted with 'must have' priority in order to make our app buildable without local SNAPSHOT of Bytecoder.

Those include the following:

*  [add missing methods putShortUnaligned putIntUnaligned](https://github.com/mirkosertic/Bytecoder/pull/474)
* PR to be created: Int16Array
* ... (investigate for more PRs)

**Comment by keesvandieren** [comment]
PRs created, waiting for reaction of maintainer.

**Comment by CoenRijsdijk** [comment]
PRs accepted by maintainer. Issue still open for more PRs in future
