### ISSUE TITLE
Spike: Bytecoder JS backend

### ISSUE THREAD

**Issue by keesvandieren** [squins/gdx-backend-bytecoder#17]
We once turned backend into JS, compilation of Maven was working and much faster then WASM.

Things to research:

* Can we (easily) support both JS and WASM  together?
* Test: with and without Exception handling
* How easy is it to get JS backend to work?
* Document alternative build structure

**Comment by CoenRijsdijk** [comment]
JS and WASM support both available in app now.
Refers to commit: https://github.com/squins/gdx-backend-bytecoder/commit/d9f523b8eab7f165f4f4666963dc0302ed282519
