### ISSUE TITLE
Make SpriteBatch instantiation pass with Bytecoder

### ISSUE THREAD

**Issue by keesvandieren** [squins/gdx-backend-bytecoder#2]
When running the app with Bytecoder, creating a new SpriteBatch instance crashes.

Some investigation has been done already by @tommyettinger in [Bytecoder issue 467](https://github.com/mirkosertic/Bytecoder/issues/467)

We also investigated that new SpriteBatch instantiation depends on WebGL (e.g. ShaderPrograms have to be implemented). ShaderProgram support is now working well in our backend.

Next steps:

* Retry SpriteBatch instantiation with our new WebGL implementation
* Analyse the investigation  done in Bytecoder issue 467
* Analyse how GWT, TeaVM libgdx backend work on this point.
* Further analyse what is to be done to make SpriteBatch instantiation pass.

**Comment by keesvandieren** [comment]
Basics works!

Steps remaining:

* Merge to master
* Improve instructions in README
* Test instructions on README

**Comment by CoenRijsdijk** [comment]
Spritebatch works succesfully on master branch
